### ISSUE TITLE
* should match words with dashes

### ISSUE THREAD

**Issue by bjornstar** [bjornstar/Tumblr-Savior#14]
I have a filter "ask * a question" but it fails to block ask posts from people with dashes in their username.

Ask asdf-asdf-asdf a question should be blocked with that filter.

**Comment by jristz** [comment]
Also if I whitelist something like "ask-your-shelf" it will hightlight
either the variant wth hyphenation and the one without hyphens.
an the same for blacklist.

2015-03-13 0:36 GMT-03:00 Bjorn Stromberg <notifications@github.com>:

> I have a filter "ask * a question" but it fails to block ask posts from
> people with dashes in their username.
>
> Ask asdf-asdf-asdf a question should be blocked with that filter.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bjornstar/Tumblr-Savior/issues/14>.
>



-- 
*Pablo Lezaeta*

**Comment by bjornstar** [comment]
@jristz I'm not sure I follow. Could you give me a specific example?

What I imagine is happening in your case is there is a URL matching "ask-your-shelf" while the text says "ask your shelf"
