### ISSUE TITLE
Plans to certify for Safari 9/OS 10.11?

### ISSUE THREAD

**Issue by smlombardi** [bjornstar/Tumblr-Savior#32]
Are you planning to re-work this into a certified (or whatever Apple's term is) extension on the new extension exchange for Safari 9?

**Comment by bjornstar** [comment]
Yeah, I'll need to look into how to set it up. I wonder if the format is backwards compatible.

**Comment by bjornstar** [comment]
So it looks like it costs real money to be able to sign an extension for safari.

I need to do something about asking for donations to pay for a cert since I don't run OS X and have no need for the extension myself.

**Comment by smlombardi** [comment]
I'm an Apple Developer.  If I have time I'll look into forking this, with your permission of course.

**Comment by bjornstar** [comment]
I got a few donations and made up the difference for the developer certificate. I released v0.4.28 very quietly because I don't have a Mac to test it on.

Not sure how sustainable this is going to be. $100/year to create free Safari extensions seems pretty lame.
