### ISSUE TITLE
bad defaults

### ISSUE THREAD

**Issue by nightpool** [bjornstar/Tumblr-Savior#35]
Hey, I help develop New XKit. We get a lot of support requests (about one or two a week) from users who are very confused about why they can't see recommended blogs or the radar. Inevitably, these users realize that this is actually a setting on Tumblr Savior. Can you rethink having these on by default? It seems to be incredibly confusing for users, and is a hassle for us to deal with personally, due to the misaimed support requests when users blame New XKit.

(same with hide source—I don't know why you would even have the option, much less as a default?)

**Comment by nightpool** [comment]
Would appreciate a response on this, as we've gotten 5 support requests this week on this issue alone.

tagging @wolvan who probably should know about this for support reasons.

**Comment by Wolvan** [comment]
Thanks for the tagging, @nightpool. I faintly remember this being Tumblr Savior's functionality from before, but thanks for confirming this

**Comment by bjornstar** [comment]
I've read your concerns, but I'm happy with the defaults I have set for my extension. The settings are very clear and easy to change within Tumblr Savior.

**Comment by nightpool** [comment]
With all respect, I've heard from dozens upon dozens of users who didn't
even know tumblr savior HAD these options, much less that they were active.
Specifically, hiding the post source bar is a very user-unfriendly change
and significantly hurts the UX of interacting with a tumblr post. Not to
mention that it goes strongly against the creators-first philosophy that
tumblr community norms embody. I urge you to reconsider on this one.
