### ISSUE TITLE
Tumblr now redirects outbound links for no good reason

### ISSUE THREAD

**Issue by Ketsuban** [bjornstar/Tumblr-Savior#36]
It looks like the destination URL is embedded in there; can Tumblr Savior dynamically replace these warts with the actual URLs?

**Comment by bjornstar** [comment]
It would be my pleasure. I find that behavior very irritating as well.

**Comment by bjornstar** [comment]
Oh god, they made all links on all blogs go to `t.umblr.com/redirect` this is way worse than I thought.

**Comment by bjornstar** [comment]
I'm releasing v0.4.24 with an option for this. Thanks for the motivation!

**Comment by Ketsuban** [comment]
Not at all, thanks to *you*.

**Comment by Ketsuban** [comment]
Seems not to be removing t.umblr.com redirects on blogs themselves—my test case is http://kaiowut99.tumblr.com/post/87571682597/my-subbedgx-stream-link-masterpost since a) there's a lot of them and b) it's where I first noticed it.

**Comment by bjornstar** [comment]
As I mentioned in [my blog post](http://bjornstar.com/post/137739495511/tumblr-savior-v0424-released-you-may-have), I can't really do anything about tumblr sticking it on all of our blogs except complain. Tumblr Savior only runs on www.tumblr.com, and not on all websites.

I am kind of inspired to make an extension that specifically kills all the redirects.

**Comment by Ketsuban** [comment]
Ahh, okay.
