### ISSUE TITLE
TS Targeting posts where a term is in the blog's profile

### ISSUE THREAD

**Issue by Icy-of-Melbourne** [bjornstar/Tumblr-Savior#39]
Hello,
Apologies if this isn't actually an issue, at the very least it seems like odd behaviour.

One of my blacklisted terms is I have 'nsfw*'. It's typically a good catch-all, though today I found it seemed to hide a post because despite the term not being in the post, the description in the OP's blog (you know, the excerpt that shows up when you hover over their url) contained 'NSFW'.

![notnsfw](https://cloud.githubusercontent.com/assets/18729501/14906003/0fa019ec-0dfa-11e6-9065-23eaafd46b56.png)

Or at least I believe this is what's going on.

**Comment by bjornstar** [comment]
The odd behavior you're talking about is the power that Tumblr Savior gives people to block things like `.gif` or `Без названия`. The power to be warned before seeing something you'd rather not see.

I tend to err on the side of getting more false positives than missing a post that should be blocked. It's much safer to block posts that *could* contain that thing you don't want to see than to ignore the signal that it's potentially there and show it without any warning. 

Tumblr Savior was never intended to be an infallible filter that perfectly blocks only the things you don't want to see. It's an alert system to hide posts when they may have some content that you've specified.

For the particular example you're showing here, some people would say the language is NSFW. Maybe the author did a good job putting NSFW in his blog description and Tumblr Savior did a good thing to warn you that the post is potentially NSFW.

I think this is working as intended.

**Comment by Icy-of-Melbourne** [comment]
Interesting point; I hadn't considered it in that respect
