### ISSUE TITLE
Blacklist phrases in adverts

### ISSUE THREAD

**Issue by IBBoard** [bjornstar/Tumblr-Savior#40]
Tumblr has started adding adverts for all sorts of junk. While I understand that they want to make money, I don't to keep having to scroll past the same adverts for things I have absolutely zero interest in (like wedding stuff on ebay!)

I've tried adding words and phrases from the ads to the Blacklist, but it doesn't seem to block the ads. My guess is that blacklisting only works on `<li class="post_container">` and not `<li class="standalone-ad-container">`.

Is it possible to make the blacklist work on adverts as well, so that I can block the annoying ads without just disabling all Tumblr ads. After all, if they're willing to show me something reasonable and not be too intrusive with it then I don't mind seeing the odd advert to support the service.

Thanks.

**Comment by bjornstar** [comment]
There's an option to hide yahoo advertisements. Could you give that a try?

**Comment by IBBoard** [comment]
No, it probably filters some bits, but doesn't seem to be getting everything. I've enabled it, no change. Refreshed the page, no change. I still get eBay ads, and I've just seen a "LeoVegas" ad that I'd rather block. They are beap.gemini.yahoo.com URLs, though, if that's what the code looks for.

Also, I'd rather do specific filtering instead of blocking everything. If I wanted all ads to go then I'd use uBlock and block ".standalone-ad-container", but I'd rather be more specific (unlike the rest of the Internet, where there is just SO MUCH ADVERTISING that I'd never be able to filter it one by one - and the ads are normally just images, not words)

Thanks.

**Comment by IBBoard** [comment]
Just revisiting this after finding out [how excessive EasyList is in adblockers](https://www.troyhunt.com/ad-blockers-are-part-of-the-problem/) and trying to see if I can get a fairer balance.

If I disable Yahoo ads then I don't get the ones on the right, but I still get the in-line ones (sponsored posts) from eBay and Vauxhall and other companies. If I hide sponsored posts then they all go away, but as some aren't intrusive then I feel that's bad and that it just fuels the "adblockers are evil" complaints.  I'm fine with some of them (the occasional Finding Dory advert, etc) but eBay are so persistent on things that I'd never buy that I want to blacklist all eBay ads!

Unfortunately, it seems that adding "eBay" to the blacklist, or the tagline of one of their ads, doesn't work. I'm assuming this is because Tumblr Savior doesn't see it as a post.

**Comment by bjornstar** [comment]
I'm not really interested in writing an ad filter. I filter posts, which are content that I subscribe to. Ads are things that I did not subscribe to, they're just getting stuck in my feed and aren't even classified as posts or tagged. They break all the rules of good content.

**Comment by IBBoard** [comment]
I wasn't asking for an ad filter, just an extension of the filtering behaviour to make it apply to every post-like-thing that is an ```<li>``` under ```<ol id="posts">```. I'd assumed that as you're already parsing the dash then it should be a simple addition to check the content of posts as well. I've looked at the HTML and while they're different, they're not worlds apart in a way that would make it impossible.

I can see your point that they're not content from people you followed, but as I'm using Tumblr and they're being friendly in not being too intrusive or animated then I feel it is reasonable to allow the majority of them. For adverts on a Yahoo-run website then they _are_ well behaved content, IMO.

I guess I'll have to find a new Tumblr-altering extension now, because I want a mid-ground between blocking everything and blocking nothing. Thank you for your time developing the extension while it met my needs, I'm just sorry you feel that way about adverts and don't want to improve people's experience on Tumblr while giving them a choice to see a subset of adverts.
