### ISSUE TITLE
Ads containing blocked keywords + show notification + hide ads

### ISSUE THREAD

**Issue by KimikoMuffin** [bjornstar/Tumblr-Savior#41]
The advertising-blocker seems to be working perfectly fine in Firefox. However, if a dashboard-advertisement contains a keyword which I'm blocking, and "show a notification when something has been hidden" is enabled, I get the whole "**Apple** has made a post containing 'iphone'"-type message, which simply disappears when I click on it.

**Comment by bjornstar** [comment]
It's really weird, but I didn't see this issue until just now.

I know what's causing it, I'll see what I can do about this.
