### ISSUE TITLE
Ads containing sound in auto-play even if posted add is blocked

### ISSUE THREAD

**Issue by jristz** [bjornstar/Tumblr-Savior#45]
So Tumblr now is rolling an update that make auto-play videos, the sound get auto-play even if the ad is blocked.

so fat I read that the video come from yimg.com (Youtube itself) and vt.tumblr.com

I personally havent see an add of these, so I can repport but I see many many posts reporting them.

so be awared

**Comment by bjornstar** [comment]
In v0.4.28 I included the sidebar ad container as a yahoo ad that can be hidden, but it won't stop the audio from playing.

I think removing the node from the DOM will stop the ad from making noise, but it's not something I want to do with Tumblr Savior. Personally I use a hosts file (https://github.com/bjornstar/hosts) so I never see it.

**Comment by jristz** [comment]
I get one but I was unable to identify the ad, I reach the conclution that tumblr-savior block the ad efectively but will not prevent the sound of the ad to auto-play.

I will try to research a little more.

**Comment by jristz** [comment]
OK now tumblr introduce an video+sound add that not even adblock block.

the option in tumblr-savior to block ads not wor with this one so we have something.

**Comment by bjornstar** [comment]
I haven't heard much about auto-playing sound lately. Feel free to re-open if it's still an issue.
