### ISSUE TITLE
Blacklist specific sponsored post accounts

### ISSUE THREAD

**Issue by IBBoard** [bjornstar/Tumblr-Savior#47]
As an addition/alternative to #40, it'd be good if we could blacklist specific account names from sponsored posts.

For example, I've had an ad from The Sun newspaper about how the Great Barrier Reef is dying. In general, I'd be fine with a news outlet showing an occasional advert for an important story that they wanted to promote, but [as The Sun is a hate-filled rag and not a source of quality journalism](https://en.wikipedia.org/wiki/Stop_Funding_Hate) then I *never* want to see one of their adverts again. 

Unfortunately, there was nothing I could block in this case. If I blocked "The Sun" then I'd get collateral damage of blocking other posts talking about astronomical bodies, and if I blocked words from the tagline then it'd probably do the same.

What I think it needs is either a separate block list or a different notation (@name?) to allow us to mute specific accounts (including when they are sponsored posts).

Thanks.

**Comment by bjornstar** [comment]
They're not accounts, they're not posts, they're advertisements. They do not participate in the community, you cannot reblog them, like them, block them, send them an ask or even @mention them. I'm not going to treat them like content.

**Comment by IBBoard** [comment]
Sorry, I was being lax with my terms. I realise that most of the adverts will be from groups that don't actually have accounts and that they're just made to look like posts so as to be in-keeping with the general dashboard display. By "account" I meant "thing that is in the account name position in an advert that is rendered as if it were a post".

**Comment by IBBoard** [comment]
In case anyone wants it, here's a patch I've been using for about three months without any problems:
[TumblrSavior.patch.txt](https://github.com/bjornstar/Tumblr-Savior/files/822032/TumblrSavior.patch.txt)
It applies existing content matching rules to the content of ad-posts, and has an "@username" notation for the fake blog name (so "@eBay" blocks eBay ads without blocking someone talking about what they just sold on eBay).
