### ISSUE TITLE
Clicking on a blacklisted post opens a new window to the poster's blog.

### ISSUE THREAD

**Issue by KimikoMuffin** [bjornstar/Tumblr-Savior#49]
It seems that Tumblr's changed some of the UI behavior *again* ... When I click on the "**dennys** made a post containing **stuff**" on the dashboard to unhide it, it shows the hidden post, but also opens a link to the poster's blog ("dennys.tumblr.com" in this example).

**Comment by nyna237** [comment]
Yeah same issue. I have found if I click way on the far right corner of the hidden post box it won't do it.

**Comment by bjornstar** [comment]
This should be fixed in v0.5.1, if you're using Chrome, Opera or Safari you should be automatically upgraded already.

Firefox users must wait for the Add-On review team to approve the new version. It's been pending review for one day now.

**Comment by KimikoMuffin** [comment]
Awesome.
