### ISSUE TITLE
Blacklist keeps resetting

### ISSUE THREAD

**Issue by Clover-Indigo** [bjornstar/Tumblr-Savior#58]
The blacklist I've established keeps getting reset somehow. I'll put in several keywords covering Tumblr posts I'd rather not see only for my next browsing experience to then have any posts relating to iPhones and iPads filtered out instead.

**Comment by bjornstar** [comment]
This should be resolved with version 2 of Tumblr Savior, it saves the settings in the extension storage instead of browser storage.
