### ISSUE TITLE
Posts in the search engine keep turning blank.

### ISSUE THREAD

**Issue by Clover-Indigo** [bjornstar/Tumblr-Savior#59]
It seems that when posts containing undesired keywords are being filtered from my search, other posts will sometimes inexplicably go blank with no way for me to get around it except to scroll back up.

**Comment by Clover-Indigo** [comment]
Good to know! I didn't even realize that I such an option for searching was available.

**Comment by bjornstar** [comment]
In the new version of the dashboard, this actually works now.
