### ISSUE TITLE
Tumblr script update broke Saviour.

### ISSUE THREAD

**Issue by CinderBH** [bjornstar/Tumblr-Savior#60]
Tumblr has been updating scripts and they broke both Saviour and the Tumblr Classic Blue script. Saviour doesn't load correctly on page load, but if you open the panel and click Save it works again until the page is reloaded.

**Comment by bjornstar** [comment]
It seems to be working for me, I tried blocking Halloween and reloaded a bunch of times. Are there any errors in the console? Which browser are you using?

**Comment by CinderBH** [comment]
A console check shows the following errors (pardon the machine translation, but it should be fine):

- The <script> source URL is not allowed in this document: "https://assets.tumblr.com/assets/scripts/tumblr/dashboard/px.js?ch=1?_v=0". Dashboards: 229: 1
- Blocked multi-origin request (cross-origin): the source matching criterion does not allow reading the remote resource from https://assets.tumblr.com/assets/scripts/tumblr/dashboard/px.js?ch=2 ? _v = 0. Reason: CORS request failed.

- The <script> source URL is not allowed in this document: "https://assets.tumblr.com/assets/scripts/tumblr/dashboard/px.js?ch=2?_v=0". Dashboards: 229: 1
- Loading failed for the <script> with source "https://fc.yahoo.com/sdarla/php/client.php?f=1197719150". Dashboards: 1: 1
- Failed to load for <script> with source "https://www.tumblr.com/assets/scripts/tumblr/dashboard/showads.js". Dashboards: 1: 1
- Failed to load for <script> with source "https://s.yimg.com/av/gemini/ga/gemini-iframe.js". Dashboards: 1: 1
- window.controllers / Controllers is deprecated. Do not use it to detect the browser User Agent.

**Comment by bjornstar** [comment]
Hmm, none of those look like an issue with Tumblr Savior. When you say it's broken, it just doesn't filter? It kind of sounds like an issue with the saved settings. Can you send them in an e-mail to bjorn@bjornstar.com?

**Comment by CinderBH** [comment]
Basically, it doesn't trigger on a new page load, but if I open the Saviour panel and click save it works again until I close or reload the page. Anyway, I'll send the settings.

**Comment by bjornstar** [comment]
Weird, which browser? I see your settings and everything looks fine there.

**Comment by CinderBH** [comment]
Firefox 70.0.1 32bit.

**Comment by bjornstar** [comment]
I just updated Firefox to v70 and I don't see any problems, there could be some tumblr changes that have not been rolled out over here yet. I'll keep an eye out for trouble.

**Comment by drmstwizard** [comment]
+1 (Also Firefox 70)

**Comment by bjornstar** [comment]
I'm unable to reproduce this issue. It works on my dashboard with endless scrolling and without. Could you give me any more ideas on how to reproduce it?

**Comment by drmstwizard** [comment]
The only thing I did was update Firefox to the most recent version.

**Comment by bjornstar** [comment]
Are you also using the 32-bit version of Firefox?

**Comment by CinderBH** [comment]
I may have finally figured it out. The source of the issue was memory leaks on Firefox that eventually caused *all* extensions to shut down.

**Comment by bjornstar** [comment]
I'll consider this resolved then. If you run into more problems and can identify what's causing it feel free to re-open.
