### ISSUE TITLE
Make compatible with 2020 design update

### ISSUE THREAD

**Issue by Schyrsivochter** [bjornstar/Tumblr-Savior#61]
There’s been a website redesign in beta for a while now which, among other things, brings colour palettes and uses the same typeface as the mobile app(s) for the website. Today it seems to have been rolled out, and now Tumblr Saviour fails to hide everything it’s supposed to – sponsored content, posts with blacklisted words …

**Comment by bjornstar** [comment]
Unfortunately they're using CSS modules which makes it incredibly painful to support.

I'm currently trying to figure out how to identify when react has finished hydrating the page so I can insert DOM elements without react removing or mutating them.

It's taking a long time to get anything going.

**Comment by bjornstar** [comment]
v1.0.0 works for the new dashboard. Google has leveraged the coronavirus pandemic to further reduce support for browser extension developers so it's unclear if it will ever roll out for Chrome users. It's been pending for 4 days now and their current plan is for extensions to take more than 3 weeks to review.

I have submitted to Opera and Firefox today and we'll see how quickly they roll it out. Firefox actually shows the length of the queue and we're in position 8 of 8 so it looks like it should go quickly.
