### ISSUE TITLE
no settings are applied 

### ISSUE THREAD

**Issue by thaliel** [bjornstar/Tumblr-Savior#62]
The newest version is not appklying any of the settings I have set it to. It doen't hide specific tags, it doesn't hide radar or recommended blogs, it basically does not work at all, even with me not using tumblr beta version

**Comment by bjornstar** [comment]
Could you please tell me which version you have installed on which browser?

**Comment by thaliel** [comment]
v 1.0.1 on firefox 75.0

**Comment by bjornstar** [comment]
I just updated to Firefox v75 and it's working fine for me, other than showing me that I didn't fix the warning icon bug that I thought I did.

Could you right click on your dashboard and choose "Save Page As..." and send the html document to bjorn@bjornstar.com?

**Comment by bjornstar** [comment]
@thaliel v1.1.0 has just been released on the Firefox Add-On site. Could you try updating to that version and giving it a whirl?

**Comment by bjornstar** [comment]
Oh, I re-read your comment, you can install v0.5.7 from https://addons.mozilla.org/en-US/firefox/addon/tumblr-savior/versions/ to use Tumblr Savior on the old dashboard.

**Comment by thaliel** [comment]
this might be a stupid question, but how do I install the older version?

**Comment by bjornstar** [comment]
> this might be a stupid question, but how do I install the older version?

For the old version of the tumblr dashboard:

Visit https://addons.mozilla.org/en-US/firefox/addon/tumblr-savior/versions/

If you currently have Tumblr Savior installed, remove it by clicking on any of the Remove buttons on the page.

![Firefox-Remove-First](https://user-images.githubusercontent.com/20630/79002217-f38c8f80-7b8a-11ea-8c2f-39569cc52738.png)

Then you install v0.5.7 by clicking the Add to Firefox button in the section labelled v0.5.7

![Firefox-Install-Old-Version](https://user-images.githubusercontent.com/20630/79002309-26368800-7b8b-11ea-9b29-1a0388e9ded8.png)

If you want to use the new version of the dashboard with Tumblr Savior, you can switch to the latest version by clicking any of the remove buttons and then choosing the Add to Firefox button on the latest version.

**Comment by thaliel** [comment]
I don't want to loose my blacklist entries, so I think I will just switch to the new dashboard

**Comment by bjornstar** [comment]
You can copy your settings from the Load/Save tab in the Tumblr Savior options page. They are backwards compatible so you can use them in both places.
