### ISSUE TITLE
blacklist not working

### ISSUE THREAD

**Issue by thaliel** [bjornstar/Tumblr-Savior#65]
Posts containing blacklisted tags are not being hidden at the moment. Using most current version of tumblr savior on the new dashboard with most current firefox

**Comment by bjornstar** [comment]
The first 2 or 3 times I loaded the dashboard it didn't block posts. After I refreshed a few times everything was working. I'm not sure what's going on, but it's possible they are rolling out a change. 

If you're still seeing the problem, could you right click your dashboard and choose "Save Page As..." and send the html file in an e-mail to bjorn@bjornstar.com?

**Comment by des1235** [comment]
I have a similar problem. I'm not using the new dashboard though.
Version 0.5.7 was working fine for me until today, with the old dashboard (I use the new xkit option to switch back to it through settings) but I was automatically upgraded to 1.1.0 without my knowlege and now Tumblr Savior is not working. Is there a way I can downgrade back to 0.5.7? I'd try to build the source on github myself but it looks like it's meant for Safari? (I'm on an Opera browser).
Do you have any plans to support the old dashboard?

**Comment by bjornstar** [comment]
It's working fine for me on Firefox and Chrome, if you can provide more details I can look into it.
