### ISSUE TITLE
"Hide sponsored posts" option hides posts in the queue

### ISSUE THREAD

**Issue by AprilSylph** [bjornstar/Tumblr-Savior#68]
Installing Tumblr Savior hides all posts in the queue by default.
Unticking the "Hide sponsored posts" option unhides them.
Hopefully this is not intentional behaviour.

**Comment by bjornstar** [comment]
Yeah, it's unintentional. I'm still looking for a solution.

**Comment by bjornstar** [comment]
I went ahead and fixed it, it has been released in v1.2.0
