### ISSUE TITLE
Rethink hiding reblog headers by default

### ISSUE THREAD

**Issue by AprilSylph** [bjornstar/Tumblr-Savior#69]
In the last week, I've had to inform at least a dozen people that comment attribution is being hidden by Tumblr Savior, not XKit or Tumblr itself. This is obviously a great source of confusion for users, and Tumblr Savior doesn't appear to have any form of user support other than this issues page.

I'll paste some messages we've gotten in the XKit support server regarding this. These are all from the past three days, all from different people:

> i don't know if this is xkit or not but with the new update people's urls don't show up in post comments.

> Q: all the posts on my dashboard aren't showing icons/usernames for who made the post. It's just text, line, text, line, text. Is that a broken xkit thing or is that tumblr being stupid?

> Question, (and if this is the wrong place to ask, lmk) With the new dash is there any way to see the profile of whoever has reblogged posts?
In this picture a 3rd party posted this, I reblogged it saying I was Mod Angie of the event, but when my friend reblogged the post without adding a comment (she's the one with the icon on the left) it doesn't show that I reblogged it saying that I was Mod Angie. This has the effect of looking like she is saying she's Mod Angie and she's not. It's confusing. ![image](https://cdn.discordapp.com/attachments/317335902810537985/728304261938544640/unknown.png)

> Is there at last going to be some update that will add the URL and icon in reblog chains? The lack of break in long reblog chains as well as the lack of being able to descern who is even participating and saying what has been making it difficult for me to brows

> also, we don't see who says what in a reblog chain anymore? usernames are yesterday's jam??

> hey, i'm not able to see on my dash who originally made each post, or in a long conversation, there's no indication of who said what, they're just separating it by a line. is this a feature of the new dash or is something going wrong? is there an xkit extension i'll have to uninstall to get it going correctly?

> did anyone else's dash just suddenly change font and become impossible to see who OP is

> Hi good people, does anyone know why my dashboard doesn't show me the URLs of people anymore when they have commented on a post? All I see are weird lines but no urls anymore and it's bugging me, does anyone know how to help me out?

**Comment by bjornstar** [comment]
Here are a few examples of the "reblog headers" I prefer to hide:

![tumblr-bad-reblog-header-1](https://user-images.githubusercontent.com/20630/86510623-5dd06b80-be2c-11ea-9456-666cf7abb00f.png)
![tumblr-bad-reblog-header-2](https://user-images.githubusercontent.com/20630/86510624-5f9a2f00-be2c-11ea-8e32-7551168855df.png)
![tumblr-bad-reblog-header-3](https://user-images.githubusercontent.com/20630/86510626-61fc8900-be2c-11ea-9d85-5e41a253cfa8.png)
![tumblr-bad-reblog-header-4](https://user-images.githubusercontent.com/20630/86510627-645ee300-be2c-11ea-80f1-9594e3e05a96.png)
![tumblr-bad-reblog-header-5](https://user-images.githubusercontent.com/20630/86510629-66c13d00-be2c-11ea-99b5-6838498f027c.png)
![tumblr-bad-reblog-header-6](https://user-images.githubusercontent.com/20630/86510788-e00d5f80-be2d-11ea-9542-875a364def5c.png)

I feel like they are a waste of vertical space and the dashboard is better with them hidden.

Although, this one does makes a bit more sense with the "reblog headers":

![tumblr-ok-reblog-header](https://user-images.githubusercontent.com/20630/86510980-ad646680-be2f-11ea-9df6-b3a0a56b1fe1.png)

Overall, I prefer the "reblog headers" hidden. It's nice that there is an option to control it for those people who hold a different opinion.

![tumblr-savior-v1 1 0-settings](https://user-images.githubusercontent.com/20630/86511309-cc182c80-be32-11ea-9b97-7b202cd1d51d.png)

I'm happy with the defaults for my extension. Thanks for stopping by.

**Comment by AprilSylph** [comment]
there being an option to control it isn't a true solution when your users are unaware that it's an option at all. does confusing users not matter because you're happy with it?

**Comment by bjornstar** [comment]
> there being an option to control it isn't a solution for users who are unaware that it's an option at all. does confusing users not matter because you're happy with it?

I think users should be responsible for understanding what their extensions do. I've purposely kept the number of options in my extension small to reduce the amount of support that I need to do.

I'll keep what you've said in mind. If at some point tumblr decides to remove the redundant reblog headers, I'll be happy to remove that option. Who knows, maybe one day I'll become annoyed at not seeing reblog headers on my dashboard and take the time to figure out how to only hide the redundant ones.

**Comment by mtae** [comment]
Fwiw, here to add that I've gotten confused by this specific point twice now over the years and eventually found that the culprit was tumblr savior after quite a bit of searching options in other extensions.
