### ISSUE TITLE
Scrolling up using the 'k' key is broken

### ISSUE THREAD

**Issue by rchard2scout** [bjornstar/Tumblr-Savior#7]
When a post is hidden, trying to scroll up on that page using the 'k' key no longer scrolls up an entire post. Instead, it scrolls up a few pixels. This only happens on a page where a post is blocked, and it doesn't matter whether or not a notification is shown.

**Comment by bjornstar** [comment]
I really wish I knew what caused this, I generally don't use the j & k shortcuts when I'm on tumblr. I'd really love it if someone could figure out how to fix it.

**Comment by Izzette** [comment]
I'll look into it.

**Comment by Izzette** [comment]
Okay, I've installed the latest pull of Tumblr-Savior into the Firefox nightly-build.  And, I was able to reproduce the bug.

**Comment by agnesnutter** [comment]
Any updates on this bug?

**Comment by JogaLuce** [comment]
I am not able to reproduce this bug in ff33.0.1 && ts0.4.22.1.

**Comment by bjornstar** [comment]
Actually, I may have this fixed for the next release ;)

**Comment by bjornstar** [comment]
Fixed in v0.4.25
