### ISSUE TITLE
tumblr savior hiding posts in likes ?

### ISSUE THREAD

**Issue by findingyouagain** [bjornstar/Tumblr-Savior#70]
I'm having an issue where a few posts that are in my likes are not showing up on the likes page while on desktop when TS is enabled. Even if I have all the options turned off in TS's settings, as long as it's enabled, these posts are being hidden. They show up when I'm in the app and when TS is disabled, but if TS is enabled the post isn't showing up in my likes ( and actually also when I click on the person's blog ( i.e. like scrolling through their posts using /dashboard/blog/url ) or when I open up their blog in a new tab. But the post still exists, I'm not blocked by the user (we're mutuals and she's aware of the issue), and it is showing up when TS is disabled / I'm on the tumblr app.

It's also not a pinned post, in case that helps narrow down the bug.

I think it's happening with more posts than just this one mutual of mine, but I'm ADHD and I honestly cannot 100% remember what all of the posts I've liked today are / who I liked them from, but my likes do seem to have less posts in them from today than I recall liking.

I hope this gets fixed soon :) I appreciate all the hard work you all are doing as I rely on TS for hiding sponsored posts, so thank you all so much & have a good day !

**Comment by bjornstar** [comment]
Everything seems to be working fine for me on the likes page. Could you point me to a specific post that is being blocked? And could you give me your settings?

**Comment by findingyouagain** [comment]
Hi! Thanks for getting back to me so quickly. My likes page appears to be working normal except on a few posts where it seems to be hiding them, even though I see them in there as the page is loading. As soon as it's fulled loaded, however, the posts disappears. As of last night, it, also doesn't show up if I go to said person's dash only view, or even when opening their blog in a new tab.

I'm not sure what all post it is affecting, but the one I noticed it on was this ( https://becauseseaotters.tumblr.com/post/622681145138675712/13valeyarx-and-wh-master-fighting-over-you ). Actually, this was the second post I could concretely say it happened on as it occurred the night before as well with another post from the same person ( the reason I say concretely is bc I know for a fact that I am not blocked by this person as we're mutuals and still able to contact each other & while it seems my likes do have more that have disappeared, not everything as some stuff shows just fine, I can positively say it happened to this one ). I checked with them and neither post it occurred on was pinned, and neither seemed to contain anything tumblr would "filter" out. None of the words in the tags were on my blacklist, and I had in fact, turned my blacklist off all together and it still occurred.

Now I did notice not with that post but the one I had first saw the issue occur that it also hadn't shown up in /tagged on both the dashboard and their blog, and miraculously without any setting changes, the next morning it was there as if it had never happened 🤷‍♀️ ( although I might have disabled TS while checking something else and that might be why as I think it disappeared again later but I do not remember ).  But then later that night, the same issue occurred on the post above.

As for my settings, I normally have the "hide recommend, hide sponsored, and hide tumblr redirects," as well as "hide source attribution", but even after I had turned off my blacklist and had unchecked off everything that seemed it would hide something, it was only after fully disabling TS in the Chrome extension settings that the post appeared.

**Comment by findingyouagain** [comment]
Again, thank you so much for your help. I am going to go back later today to double check I had properly turned off the blacklisting features and see if that fixes it so as to save you any work if it's not a bug but me doing some
thing wrong, but I know I had already turned those features off sometime after the new dash update and had not turned them back on inbtwn when the first post disappared from my likes and when it reappeared so I'm doubtful that is the case but just to be sure 🤞 Also, even if so, nothing in the tags is on my blacklist and and had unclicked "include if in header, post itself, etc" so it shouldnt have filtered it out if I had missed something in the post that my blacklist might have caught ( the only thing I could think of might be "blood," as I have that word blacklisted and the first post might have contained that word but not the second post as far as I'm aware ,,, however, that would make somewhat sense to me as I've had really finicky results with how TS blacklists "blood" bc the post body, tags, header of post post might have no signs of the word or blood itself but if like a gifset is from a show about vampires ( for example Buffy or Angel as I noticed it did this the other day ), *# it will get hidden by my blacklist for some reason. Does TS use tags from accounts I don't follow / am not interacting with to also hide posts ( i.e. I'm trying to reblog it from one of my mutuals. Their reblog of the post has no traces of the word "blood" and neither does the op's, but if someone else in the notes had reblogged it and tagged it with "blood" would it then hide my mutuals' post even if it doesn't contain the blacklisted word or there something else going on there ) ? I've noticed this for a while, but I cannot recall when it first started occurring, but it was long before the new dash update.

Sorry I know that is slightly off topic from my main issue ( and the things overcautiously getting hidden is not a real priority to me ), but I thought I might mention it in case the weird behaviors might be related.

**Comment by findingyouagain** [comment]
> Everything seems to be working fine for me on the likes page. Could you point me to a specific post that is being blocked? And could you give me your settings?

Okay, I checked again and it seems like it was supposedly just being blocked by my something on my blacklist, even though I thought I had unchecked it. Sorry for the bother ! Thank you so much for your help again !

**Comment by bjornstar** [comment]
> > Everything seems to be working fine for me on the likes page. Could you point me to a specific post that is being blocked? And could you give me your settings?
> 
> Okay, I checked again and it seems like it was supposedly just being blocked by my something on my blacklist, even though I thought I had unchecked it. Sorry for the bother ! Thank you so much for your help again !

Cool, no problem. Glad it's working for you!
