### ISSUE TITLE
hide sponsored ad

### ISSUE THREAD

**Issue by thaliel** [bjornstar/Tumblr-Savior#71]
on the dahbiard, there is now a new sponsored ad in the upper right area

**Comment by bjornstar** [comment]
I'm not seeing it, can you double check you are using v1.3.0 of Tumblr Savior?

**Comment by thaliel** [comment]
yes, my dashboard looks like this even with the most current version
![tumblrad](https://user-images.githubusercontent.com/5956255/90846774-3a746800-e369-11ea-9e0a-040e931c3a0f.png)

**Comment by bjornstar** [comment]
Can you right click and "Save Page As..." and send me the html? It's better if you put it in an e-mail to bjorn@bjornstar.com

**Comment by bjornstar** [comment]
If you're still seeing this issue, could you send me an e-mail? I can't reproduce it.
