### ISSUE TITLE
Hiding blacklisted tags and keywords doesn't seem to work

### ISSUE THREAD

**Issue by Bee-357** [bjornstar/Tumblr-Savior#76]
Hi there,

I noticed there's been an update and now it doesn't seem to be working anymore? Tumblr now shows me posts on my dashboard with tags and keywords in them that I've blacklisted through Tumblr Savior.

Thanks for your help.

**Comment by bjornstar** [comment]
I'm not seeing any problems here. Could you tell me which browser you're seeing the issue on?

**Comment by Bee-357** [comment]
Thank you for your very quick reply. I'm using Google Chrome Version 87.0.4280.88.

I've done a little experimenting, and it seems to work for some tags but not for others. I also hide posts with the Tumblr blacklisting function (blacklisting the same tags and keywords I blacklist with Tumblr Savior), but I still see the blank posts with the tags I'm trying to hide through Tumblr Savior, which didn't happen previously. They were completely hidden.

If I click on "view post" on the post that is blacklisted through the Tumblr function, it gets hidden completely instead of being displayed, meaning that Tumblr Savior seems to kick in then. So I think it's probably a Tumblr issue rather than one with your add-on.

I hope this explanation wasn't too confusing.

**Comment by bjornstar** [comment]
There's clearly some confusion when two filtering systems are in place at the same time.

In v1.7.0 I have made ignoring filtered content optional. This should allow you to go back to the previous behavior where Tumblr Savior will filter posts that are already filtered by tumblr. I also fixed the layout issue where the "Show me" button does not appear on posts that are filtered by both Tumblr Savior and tumblr.

Additionally, I have added an option to hide content that is filtered by tumblr. This will allow people to hide filtered posts completely while still using tumblr savior with notifications enabled.

I'm actually quite surprised that people preferred the previous behavior where Tumblr Savior ran on the filtered posts but I can understand the expectation that it continues to work on all posts even if they're already filtered.

Please try out the new version and let me know if the two new options work for you.

**Comment by Bee-357** [comment]
I installed the updated version through developer mode and now it all works like it did before.

Thank you so much for your explanation and your quick fix! I love your add-on because it does what Tumblr blacklisting doesn't, which is completely hide the posts I don't wanna see, and I'm very glad that it continues to do that for me now.

Again, thanks!
