### ISSUE TITLE
sponsored content and other annoyances

### ISSUE THREAD

**Issue by thaliel** [bjornstar/Tumblr-Savior#77]
Tumblr has managed to bring sponsored content back into the dashboard and sidebar. Even though the images/videos are hidden, the things themselves clutter my dashboard, as well as an annoying "check out these tags" thing and whatever this is
[https://i.imgur.com/LSlmpJA.png](url)

**Comment by bjornstar** [comment]
They completely rebuilt their CSS modules so I have to go through and remap everything.

**Comment by bjornstar** [comment]
It should be fixed in [v1.9.0](https://github.com/bjornstar/Tumblr-Savior/releases/tag/v1.9.0) pending store submission and approval.
