### ISSUE TITLE
ads and sponsered content are  back again

### ISSUE THREAD

**Issue by thaliel** [bjornstar/Tumblr-Savior#81]
since yesterday, my dashboard is once again cluttered by ads, sponsored posts, suggestions for tags and blogs etc.

it is immensely annoying

**Comment by bjornstar** [comment]
Thanks for reporting. I've already pushed out a fix with `v1.12`, it may take some time before it's available on Edge and Chrome. It's already available on Firefox and Opera.

If you try `v1.12` and still experience issues, please let me know.

**Comment by bjornstar** [comment]
`v1.12.1` is now available on Chrome. Edge typically takes 7 days, it's so bad.

**Comment by bjornstar** [comment]
This should be fixed by fc3879b, please reopen if you're still having trouble.
