### ISSUE TITLE
Tumblr Savior no longer working after July 2023 Tumblr update

### ISSUE THREAD

**Issue by doodledorp** [bjornstar/Tumblr-Savior#87]
Tumblr updated recently to a new dashboard appearance that seems to have broken Tumblr Savior (henceforth referred to as TS). TS list can be seen in extensions, tags all load into extension dropdown list, and extension seems to be running properly in isolation. However, upon entering the recently updated Tumblr dashboard, all posts containing blocked tags are fully loading in with no 'hiding' performed by TS, and no warnings. Saving settings again manually will temporarily block the post, but on page refresh it returns to being unblocked. Possibly an issue with how posts are being displayed due to the new dashboard layout.

**Comment by bjornstar** [comment]
Can you tell me which browser you are using and which region you are in? I'm not seeing any major problems in Chrome, although the blaze button is causing some minor layout issues.

**Comment by doodledorp** [comment]
Certainly - I am using Firefox 115.0.2 in North America / USA.

**Comment by bjornstar** [comment]
I'm seeing [this post](https://www.tumblr.com/changes/723204519134216192/tuesday-july-18th-2023) saying they're rolling out some navigation changes, but I don't think I've gotten it yet. 

I'll keep an eye on it and update as soon as it rolls out for my account.

**Comment by doodledorp** [comment]
Much appreciated! And thank you so much for the work that you do, it really does make browsing Tumblr a vastly improved experience.

**Comment by bjornstar** [comment]
The new version of the dashboard rolled out to me yesterday and I've released v1.15.0 today which should resolve the issues. Let me know if you run into any more problems!
