### ISSUE TITLE
Characters across newlines are treated as a single word

### ISSUE THREAD

**Issue by DizzyHSlightlyVoided** [bjornstar/Tumblr-Savior#94]
Different lines appear to be concatenated together when performing checks. i.e. a post which says

> That is a cat
>
> I like cats.

is treated as "That is a catI like cats." for the purpose of checking whether to block it.

So, for example, if you have "cati" blocked, the above post will be blocked. And whitelisting "cat" isn't an option, because maybe someone will say "Cati stepped on her cat's tail!", which you would still want blocked (or whatever).

This can probably be fixed just by joining with a space (i.e. change [this line](https://github.com/bjornstar/Tumblr-Savior/blob/a456ae5da2d395caa3c6320de444237913cc8129/src/data/script.js#L306) to say `.join(' ')` instead of `.join('')`, so that the example above is treated as "That is a cat I like cats"

**Comment by bjornstar** [comment]
Do you have a post I can reference that has this problem?

**Comment by DizzyHSlightlyVoided** [comment]
[This post](https://www.tumblr.com/dizzyhslightlyvoided/751053867868962817/the-grass-is-always-greener-on-the-other-side) when I add `platitude?"` as a keyword.

Or [this](https://www.tumblr.com/dizzyhslightlyvoided/768812502365716480/so-heres-a-little-bit-of-a-lesson-in-meme) when you put `knuckles.sega` (first two lines)

Or [this](https://dizzyhslightlyvoided.tumblr.com/post/768896192524451840/testing-a-thing-y-here) with `thingy`

**Comment by bjornstar** [comment]
Thank you for reporting this, it should be fixed in v2.1.0 which I am releasing right now.
